name: Generate AI Article

on:
  push:
    paths:
      - articles/*.md  # Specify the folder where article files are stored
    branches:
      - main  # Define which branch to trigger from

jobs:
  generate_article:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js (if your script uses Node.js)
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Check if file has AI trigger
      id: check_file
      run: |
        FILE_PATH=$(find articles -name "*.md" | tail -1)  # Customize path search as needed
        if grep -q "ai:true" "$FILE_PATH"; then
          echo "generate=true" >> $GITHUB_ENV
          echo "file_path=$FILE_PATH" >> $GITHUB_ENV
        else
          echo "generate=false" >> $GITHUB_ENV
        fi

    - name: Generate Article via ChatGPT
      if: env.generate == 'true'
      run: |
        node scripts/generateArticle.js "$file_path"
      env:
        file_path: ${{ env.file_path }}

    - name: Commit updated article
      if: env.generate == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "$file_path"
        git commit -m "AI-generated article update for $file_path"
        git push
